---
- name: Deploy App
  hosts: app
  become: true
  tasks:
    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/aleb/reddit
        version: monolith
      notify: reload puma

    - name: bundle install
      bundler:
        state: present
        chdir: /home/aleb/reddit
      notify: reload puma 

  handlers:
  - name: reload puma
    become: true
    systemd: name=puma state=restarted
...

