- name: Configure App
  hosts: app
  become: true
  vars:
          db_host: 10.132.0.33:27017
  tasks:
    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/aleb/db_config
        owner: aleb
        group: aleb
      notify: reload puma  

    - name: enable puma
      systemd: name=puma enabled=yes
      notify: reload puma

  handlers:
  - name: reload puma
    systemd: name=puma state=restarted


